version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: book-library-app
        container_name: book-library-app
        volumes:
            - ./:/var/www
        networks:
            - book-library

    webserver:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8083:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - book-library

    db:
        image: mysql:8.0
        container_name: mysql
        ports:
            - "3309:3306"
        environment:
            MYSQL_DATABASE: book-library
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: book-library
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - book-library

volumes:
    dbdata:

networks:
    book-library:
        driver: bridge
